CREATE TABLE POS(
    PID INTEGER DEFAULT 0,
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME TEXT,
    DB_TYPE,
    URL TEXT,
    PATH TEXT
);

CREATE TABLE POS_PROPERTIES(
    ID INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    PROPERTIES TEXT,
    constraint POSP_PK primary key (id, pid)
);